#import "theme/ui/atoms/Typography/Price/PriceFragment.gql"

fragment ProductPriceFragment on ProductType {
  prices {
    finalPrice {
      priceInclTax {
        ...PriceFragment
      }
      priceExclTax {
        ...PriceFragment
      }
    }
  }
}
