#import "../../modules/ProductList/ProductListFragment.gql"
#import "../../modules/HomeBanner/HomeBannerFragment.gql"

query Home($id: Int!, $params: QueryInput!) {
  category(id: $id) {
    ...ProductListFragment
  }
  store {
    ...HomeBannerFragment
  }
}
