#import "./CategoryFragment.gql"
#import "./StoreNameFragment.gql"

query HomeQuery($id: Int!, $params: QueryInput!) {
  category(id: $id) {
    ...CategoryFragment
  }
  store {
    ...StoreInformationFragment
  }
}
