#import "theme/ui/atoms/Typography/Price/PriceFragment.gql"

fragment Product on Product {
  sku
  name
  imageUrl
  description
  prices {
    finalPrice {
      priceInclTax {
        ...PriceFragment
      }
    }
  }
}

query Product($sku: String!) {
  product(sku: $sku) {
    ...Product
  }
}
