#import "theme/ui/atoms/Typography/Price/PriceFragment.gql"
#import "./Item/CartItemFragment.gql"

fragment CartFragment on Cart {
  id
  items_qty
  items {
    ...CartItemFragment
  }
  totals {
    subtotalInclTax {
      ...PriceFragment
    }
    totalInclTax {
      ...PriceFragment
    }
    totalExclTax {
      ...PriceFragment
    }
    tax {
      ...PriceFragment
    }
  }
}
